version: 0.2

phases:
  build:
    commands:
       - echo every thing is fine && yum install httpd
       - sam package --template-file cdk-test.yml --output-template-file package.yml --s3-bucket cdk-test-dheeraj